# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161214_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionsong',
            name='session',
        ),
        migrations.AlterField(
            model_name='sessionsong',
            name='session_name',
            field=models.CharField(max_length=5),
        ),
    ]
