# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161214_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsong',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
    ]
