# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161214_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='apple_id',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionsong',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.Session'),
        ),
        migrations.AlterField(
            model_name='sessionsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_serial', to='api.Song'),
        ),
    ]
