# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161214_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hype_value', models.FloatField(default=0.5)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_requests', to='api.Session')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_songs', to='api.Song')),
            ],
        ),
    ]
