# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_songcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='0', max_length=250),
            preserve_default=False,
        ),
    ]
