# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_session_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
