# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20161227_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
