# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_session_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='now_playing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Song'),
        ),
    ]
