# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_session_now_playing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='now_playing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Song'),
        ),
        migrations.AddField(
            model_name='session',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.Service'),
            preserve_default=False,
        ),
    ]
