# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170108_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
