# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170108_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='apple_id',
            new_name='serviceID',
        ),
    ]
