# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170109_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.Service'),
            preserve_default=False,
        ),
    ]
